name: Build Dev

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'MacOS ARM64'
            platform: 'macos-latest'
            assetNamePattern: 'Unoff-NKAR-Manager-[version]-MacOS-Arm64[ext]'
            args: '--target aarch64-apple-darwin'
          - name: 'Linux x64'
            platform: 'ubuntu-22.04'
            assetNamePattern: 'Unoff-NKAR-Manager-[version]-Linux-x64[ext]'
            args: ''
          - name: 'Windows x64'
            platform: 'windows-latest'
            assetNamePattern: 'Unoff-NKAR-Manager-[version]-Windows-x64[ext]'
            args: ''
          - name: 'Android ARM64'
            platform: 'ubuntu-22.04'
            assetNamePattern: 'Unoff-NKAR-Manager-[version]-Android-Arm64[ext]'
            mobile: 'android'
            args: '--target aarch64 --apk true --split-per-abi'
    steps:
      - uses: actions/checkout@v6

      - name: Decode keystore
        if: matrix.mobile == 'android'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 -d > src-tauri/gen/android/release.jks

      - name: Write key.properties  # storeFile context is in android/app/, go one level up to android/release.jks
        if: matrix.mobile == 'android'
        run: |
          cat <<EOF > src-tauri/gen/android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=../release.jks
          EOF

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # v4.2.0+ (dev)
        with:
          version: 10
          run_install: true
          cache: true

      - name: Setup Java
        if: matrix.mobile == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || (matrix.mobile == 'android' && 'aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android' || '') }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' && matrix.mobile != 'android'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ${{ matrix.platform }}-${{ matrix.mobile || 'desktop' }}

      - uses: tauri-apps/tauri-action@063c0231f444e55760d98acb9c469b994269d4a5  # v1 (dev)
        id: tauri
        with:
          args: ${{ matrix.args }}
          mobile: ${{ matrix.mobile || '' }}  # Android SDK is included in runner image (https://github.com/actions/runner-images/blob/39bd9125f9da70b40db3fcc04fe378ff2da8aecf/images/ubuntu/Ubuntu2404-Readme.md)
          uploadWorkflowArtifacts: true

      - name: Get artifact paths  # Parse list into multiline string for output; remove .app (cannot attest a directory)
        id: artifacts
        shell: bash
        run: |
           echo "paths<<EOF" >> $GITHUB_OUTPUT
           echo '${{ steps.tauri.outputs.artifactPaths }}' | jq -r '.[] | select(endswith(".app") | not)' >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT

      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ steps.artifacts.outputs.paths }}
